int ps_factor (float);
char *ps_setplt (char *, char *, char *, char *, int);
int ps_wrapup (void);
int ps_frame (void);
int ps_macro (float, float, float, char *);
int ps_plot (float, float, int);
int ps_zinc (int, int);
int ps_zrgb (int, float *);
int ps_zcmyk (int, float *);
int ps_zmark (char *);
int ps_symbol (float, float, float, char *, float, int, char *);
int hp_factor (float);
char *hp_setplt (char *, char *, char *);
char *hpgl2_setplt (char *, char *, char *);
char *hpgl2b_setplt (char *, char *, char *);
int hp_wrapup (void);
int hp_frame (void);
int hpgl2_frame (void);
int hp_macro (float, float, float, char *);
int hp_plot (float, float, int);
int hp_zinc (int, int);
int hp_symbol (float, float, float, char *, float, int);
int hpgl2_symbol (float, float, float, char *, float, int);
int bgi_factor (float);
char *bgi_setplt (char *, char *, char *, int);
int bgi_wrapup (void);
int bgi_frame (void);
int bgi_macro (float, float, float, char *);
int bgi_plot (float, float, int);
int bgi_symbol (float, float, float, char *, float, int);
int bgi_symbol6 (float, float, float, char *, float, int);
int pcl_factor (float);
char *pcl_setplt (char *, char *, char *, int);
int pcl_wrapup (void);
int pcl_frame (void);
int pcl_wrapup6 (void);
int pcl_frame6 (void);
int pcl_wrapup7 (void);
int pcl_frame7 (void);
int pcl_macro (float, float, float, char *);
int pcl_plot (float, float, int);
int pcl_symbol (float, float, float, char *, float, int);
int pcl_symbol6 (float, float, float, char *, float, int);
