#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/****************************************************************************/

static char *help_text[] = {
  "PDSDB_help() V1.0",
  "  ",
  "pds dATA bASE, routine to access the Cassini/RPWS",
  " level-2 data archive at the University of Iowa",
  " (or from a PDS archive volume)",
  "  ",
  "  This library consists of a set of routines that",
  "may be used to selectively access RPWS science",
  "telemetry.  The basic function is to access data ",
  "from a selected time range.  Additional entry ",
  "points are provided to narrow data selection.",
  "  ",
  "  Sample code for using the library may be ",
  "found in the source code to the pdsdb wrapper.",
  "See the help text for that routine for the",
  "path/filename to find the sample code.",
  "",
  "  Although we make use of SPICE (and friends) to handle",
  "time (i.e. string conversion to SCLK, there is no",
  "data product specific time decoding the the read",
  "routine.  The read will deliver data from the begining",
  "of the file that contains the start time, the user program",
  "is required to eliminate data outside the selected period.",
  "",
  "\f",
  "Routines: (pdsdb.h)",
  "  ",
  "       struct PDSDB *PDSDB_open(char *start_time, ",
  "                             char *stop_time, ",
  "                             char *path, ",
  "                             char *name, ",
  "                             char *standard_data_product_id,",
  "                             char *file_specification_name_substring);",
  "       int PDSDB_close(struct PDSDB *pdsdb);",
  "     ",
  "       struct RPWS_buffer *PDSDB_read_stream(struct PDSDB *pdsdb, ",
  "                                             char *object);",
  "     ",
  "       int PDSDB_help(FILE *output);",
  "",
  "\f",
  "Data Definitions: (pdsdb.h)",
  "  ",
  "        There are several external data definitions",
  "      in the pdsdb library that are defined in the ",
  "      header file.",
  " ",
  "    extern char *PDSDB_Version",
  "        Version number string",
  "              PDSDB_VERSION",
  "                  #define that should match PDSDB_Version",
  "                  a mismatch indicates that the header file",
  "                  and the library file do not match (bad!!!)",
  " ",
  "    extern int   PDSDB_debug",
  "        Debug flag (enumerations follow)",
  "",
  "\f",
  "Data Structures: (pdsdb.h)",
  "  ",
  "        This is the PDSDB data structure as treated by user code.",
  "      In particular, only the link field at the begining of the",
  "      structure should be written.",
  " ",
  "    struct PDSDB {",
  "                       struct PDSDB         *link;",
  "                 * * * more to come * * *",
  "                }",
  " ",
  "",
  "\f",
  "Include files:",
  "  ",
  "          These are the include files that contain the routine ",
  "        definitions and enumerations required to make use of",
  "        the PDSDB routines.",
  "        ",
  "        /opt/project/cassini/include/pdsdb.h",
  "        /opt/project/cassini/include/mdb.h",
  "",
  "\f",
  "Routines in detail:",
  "  ",
  "        Specifics and prerequisites on the use of the PDSDB routines.",
  "      ",
  "  spice initilization  <----------==========********** SPICE SPICE SPICE",
  "      ",
  "        The spice routines are used to convert SCET strings into",
  "      SCLK values used for searching the file.  We need spice in",
  "      order to be able to operate with both SCLK and SCET.  This",
  "      also results in time specifications returning data based on",
  "      current best estimate of time, so errors in SCLK/SCET that",
  "      may have been introduced when the data was received do not",
  "      affect data selection.",
  "      ",
  "        The user application is responsible for intializing the",
  "      spice routines with the current leap-seconds and the current",
  "      sclk kernels.",
  "      ",
  "        Also, note that the FORTRAN routines are used, due to a",
  "      problem with the c routines, so the appropriate linker",
  "      must be used as well as the appropriate spice library.",
  "      ",
  "        This example shows the use of ldpool, also consider",
  "      using the spice routine \"furnish\".",
  "      ",
  "      Sample SPICE initialization",
  "          ",
  "          static char *metafile = {\"$CAS_TIME_KERNELS\"};",
  "          ",
  "          furnsh_c(metafile);",
  "          ",
  "          PDSDB_open(start, stop, NULL, NULL, 0);",
  "  ",
  "\f",
  "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -",
  "  struct PDSDB *PDSDB_open(char *start_time, ",
  "                       char *stop_time, ",
  "                       char *path, ",
  "                       char *name, ",
  "                       char *standard_data_product_id,",
  "                       char *file_specification_name_substring);",
  "      ",
  "    Purpose:",
  "      ",
  "        Allocate and intialize the data structures required",
  "      to access the RPWS data.",
  "      ",
  "        This is the initilization call that establishes the ",
  "      start and stop times as well as the files that will be",
  "      selected for reading.",
  "      ",
  "        Multiple streams may be open at any time.  Simply",
  "      call the open routine while keeping track of the the ",
  "      additional PDSDB structures.",
  "  ",
  "    Arguments:",
  "      ",
  "        The 1st. argument, 'start_time' is required and may be",
  "      either a SCET string that is acceptable to spice or a SCLK",
  "      string that is acceptable to spice or a hexadecimal SCLK string.",
  "      The hexadecimal SCLK string must be exactly 8 characters long.",
  "      ",
  "        The 2nd. argument is optional, supply a NULL if it is not used.",
  "      This is the stop time and is in the same format as the start time.",
  "      When this argument is not supplied, all data after the specified",
  "      start time is returned.",
  "      ",
  "        NOTE that times are somewhat approximate as the entire contents",
  "      of the file are returned.  Time information is extracted from the",
  "      PDS label for the file",
  "      ",
  "        The 3rd. argument 'path' is the path name for the index ",
  "      file.  This argument is optional, supply a NULL if it",
  "      is not used.  There is an appropriate defualt that is used",
  "      if nothing is supplied by the user.",
  "        This string must NOT have a trailing slash (i.e. it will ",
  "      be appended by the open function).",
  "        This argument is the path to the PDS archive volume that",
  "      contains the data you are interested in.  The point in the",
  "      file system this argument points to should have the root",
  "      structure of a PDS volume (i.e. you should see the INDEX and",
  "      DATA directories at this point in the filesystem.",
  "      ",
  "        The 4th. argument 'name' is the name of the database index file.",
  "      As with the path, this argument is optional and must be a NULL",
  "      if it is not used.",
  "        The default value is \"INDEX/INDEX.LBL\", and this should",
  "      be the appropriate string for almost any configuration.",
  "      ",
  "        The 5th argument is the string from the INDEX.TAB column",
  "      labeled \"STANDARD_DATA_PRODUCT_ID\" for the data you",
  "      are extracting from the file.  The complete string is required",
  "      here (no space padding).",
  "      ",
  "        The 6th. argument is a substring contained in the ",
  "      \"FILE_SPECIFICATION_NAME column.  A NULL may be supplied ",
  "      here to select all files.",
  "      ",
  "    Return Value",
  "      ",
  "        The PDSDB structure is returned with many of the fields filled",
  "      in.  No data has been read yet, only the first label file",
  "      that matches the time and file selects.",
  " ",
  "        An invalid argument will result in the program terminating",
  "      (malformed start/stop time, for example).",
  "      ",
  " ",
  "\f",
  "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -",
  "  int PDSDB_close(struct PDSDB *pdsdb);",
  "      ",
  "    Purpose:",
  "      ",
  "        Deallocate the data structures used to access data.",
  "      ",
  "    Arguments:",
  "      ",
  "        The PDSDB structure of the stream that is no longer",
  "      to be used is supplied as the only argument to the",
  "      close routine.",
  "      ",
  "    Return Value",
  "      ",
  "        Usually returns a zero.",
  "          A non-zero value indicates that there were some resources",
  "        that were not allocated, such as buffer or file handles.",
  " ",
  "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -",
  "  unsigned char *PDSDB_read(struct PDSDB *pdsdb,",
  "                            char *record);",
  "      ",
  "    Purpose:",
  "      ",
  "        Read the next data record in the selected time period.",
  "      ",
  "        PDSDB_read returns the data from the selected files for",
  "      those files that cover the period between the specified ",
  "      start and stop times.",
  "      ",
  "    Arguments:",
  "      ",
  "        The 1st. argument is an PDSDB structure.  This is the data",
  "      structure returned from PDSDB_open.",
  "      ",
  "        The 2nd. argument is used to determine the point in the",
  "      data file that the first data record is located.  The",
  "      string that is specified here is the data pointer from the",
  "      label file.  It will be located near the top of the label",
  "      file and look something like the following:",
  "          ^KEYWORD = (\"FILENAME\", 1)",
  "        The \"KEYWORD\" is what we expect to see in the 2nd.",
  "      argument.  In this example, this indicates that we start",
  "      reading at the first record in the file.  Some of the ",
  "      datasets start on the 2nd. or 3rd. record, following header",
  "      information.",
  "      ",
  "    Return Value",
  "      ",
  "        The address of a data buffer containing the data from",
  "      the data file.  The size of the data buffer is determined ",
  "      by what is contained in the label file.  If the data is text",
  "      it will be terminated with a zero, if the data is binary",
  "      there will probably be zero bytes within the data, and the",
  "      area immediately following the data is zero filled.",
  "      ",
  "        Note that there is a single data buffer allocated and",
  "      addressed through the PDSDB structure.  Each successive call",
  "      to read data overwrite previous data.",
  " ",
  "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -",
  "  unsigned char *PDSDB_read_stream(struct PDSDB *pdsdb, ",
  "                                   int stream,",
  "                                   char *record);",
  "      ",
  "    Purpose:",
  "      ",
  "        Read the next data record in the selected time period.",
  "      ",
  "        PDSDB_read_stream returns the data for the specified ",
  "      period.  Only data from the specified period is returned.",
  "      ",
  "    Arguments:",
  "      ",
  "        The 1st. argument is an PDSDB structure.  This is the data",
  "      structure returned from PDSDB_open.",
  "      ",
  "        The 2nd. argument is an enumeration that specifies the",
  "      format of the time information within the data record.",
  "      One of the following enumerations may be used:",
  "              ",
  "              PDSDB_STREAM_RPWS_KEY_PARAMETERS",
  "              PDSDB_STREAM_RPWS_LOW_RATE_FULL",
  "              PDSDB_STREAM_RPWS_WAVEFORM_FULL",
  "              PDSDB_STREAM_RPWS_WIDEBAND_FULL",
  "      ",
  "        The 3nd. argument is used to determine the point in the",
  "      data file that the first data record is located.  The",
  "      string that is specified here is the data pointer from the",
  "      label file.  It will be located near the top of the label",
  "      file and look something like the following:",
  "          ^KEYWORD = (\"FILENAME\", 1)",
  "        The \"KEYWORD\" is what we expect to see in the 2nd.",
  "      argument.  In this example, this indicates that we start",
  "      reading at the first record in the file.  Some of the ",
  "      datasets start on the 2nd. or 3rd. record, following header",
  "      information.",
  "      ",
  "    Return Value",
  "      ",
  "        The address of a data buffer containing the data from",
  "      the data file.  The size of the data buffer is determined ",
  "      by what is contained in the label file.  If the data is text",
  "      it will be terminated with a zero, if the data is binary",
  "      there will probably be zero bytes within the data, and the",
  "      area immediately following the data is zero filled.",
  "      ",
  "        Note that there is a single data buffer allocated and",
  "      addressed through the PDSDB structure.  Each successive call",
  "      to read data overwrite previous data.",
  " ",
  "\f",
  "- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -",
  "  int PDSDB_help(FILE *output);",
  "      ",
  "    Purpose:",
  "      ",
  "        Dump the text you see here.",
  "      This documentation baggage is carried with the",
  "      program if you add a call to this module.",
  "  " "        you can always leave the call to PDSDB_help() out",
  "      an obtain a copy of this text from the pdsdb utility.",
  "  ",
  "    Arguments:",
  "      ",
  "        File descriptor, typically <stdout>).",
  "      ",
  "    Return Value",
  "      ",
  "        Line count.  The number of lines of text in this",
  "      help file.",
  "      ",
  "",
  "\f",
  "PDSDB structure in detail:",
  "      ",
  "        This is a description of the fields within the PDSDB data",
  "      structure.  User code should treat all of these fields",
  "      as read-only.  Altering the FILE structures can cause",
  "      catastrophic problems.  Altering other fields will probably",
  "      not affect processing as they are updated and used as needed",
  "      with each call to the read routines.",
  "        The fields may become read-only in a future update to the",
  "      pdsdb.h file.",
  "      ",
  "    struct PDSDB    *link;",
  "      ",
  "        Reserved for user code.  Provided to allow",
  "      creation of linked lists of PDSDB structures.",
  "        This pointer is cleared (set to NULL) when the",
  "      PDSDB_open call allocates memory for the data structure.",
  "      ",
  "    char            *database_path;",
  "        This is the starting point of the PDS data archive.",
  "      There is a default value that is appropriate for the",
  "      index at Iowa.  If you are using a CD, this would",
  "      point to the root directory of the archive volume.",
  " ",
  "    char            *database_name;",
  "        This is the name of the INDEX label, typically",
  "      \"INDEX/INDEX.LBL\".  This label points to a file",
  "      that contains a list of all files on this volume.",
  " " "    FILE            *database_file;",
  "        File handle for the index label and table.  The",
  "      label file is initially opened to extract some information",
  "      from the label, closed, then opened for the index table.",
  " ",
  "    int              database_rec_num;",
  "        Current record number within the index table.",
  " ",
  "    char            *database_detail_line;",
  "        Storage are for each record from the index table.",
  " ",
  "    int              database_seek;",
  "        Byte offset of the 1st. detail record in the index table.",
  "      (the labels will usually indicate that the first record",
  "       in the index is to be skipped).",
  " ",
  "    int              database_records;",
  "        Index table record count.  That is, the number of detail",
  "      record contained in the index table, excluding any headers",
  " ",
  "    int              database_bytes;",
  "        Record length, in bytes, of index table.  This is extracted",
  "      from the index label and subsequently used to read detail",
  "      lines from the index table." " ",
  "    char            *database_fields[PDSDB_TOKENS];",
  "        List of fields thaat appear in the index table (taken",
  "      from the index label).",
  " ",
  "    char            *pdsdb_packet_type;",
  "        String used to compare with \"STANDARD_DATA_PRODUCT_ID\"",
  "      from the index table.  This field is obtained from the ",
  "      PDSDB_open call (file selection).",
  " ",
  "    char            *pdsdb_packet_subtype;",
  "        Substring used to compare with \"FILE_SPECIFICATION_NAME\"",
  "      from the index table.  This may be a partial match",
  " ",
  "    char            *datalabel_volume;",
  "        \"VOLUME_ID\" from the index table.",
  " ",
  "    char            *datalabel_name;",
  "        Name of the datafile currently being read.",
  " ",
  "    FILE            *datalabel_file;",
  "        File handle for the data file currently being read.",
  " ",
  "    int              datalabel_sclk_cnt_start;",
  "        SCLK filed from the data label.  Derived from the",
  "      SPACECRAFT_CLOCK_START_COUNT or START_TIME line in ",
  "      the data label.  Expressed as SCLK",
  " ",
  "    int              datalabel_sclk_cnt_stop;",
  "        SCLK field from the data label.   Derived from the",
  "      SPACECRAFT_CLOCK_STOP_COUNT or STOP_TIME line in ",
  "      the data label.  Expressed as SCLK",
  " ",
  "    int              datalabel_records;",
  "        Record count, that is number of records in the data ",
  "      file.  Obtained from the data label.",
  " ",
  "    int              datalabel_bytes;",
  "        Record size, in bytes.  Obtained from the data label.",
  " ",
  "    char            *datalabel_record_name[PDSDB_TOKENS];",
  "    int              datalabel_seek[PDSDB_TOKENS];",
  "        This table has the offsets into the data file that",
  "      were extracted from the data label.  This is the",
  "      string that is matched against that passed in to the",
  "      PDSDB_read* calls.",
  " ",
  "    char            *datafile_name;",
  "        Filename of the data file currently being read.",
  " ",
  "    FILE            *datafile_file;",
  "        File handle for the data file currently being read",
  " ",
  "    unsigned char   *buffer;",
  "        Data buffer.  As mentioned above, this buffer is",
  "      allocated by the PDSDB_open call.",
  " ",
  "",
  NULL
};

int PDSDB_help (FILE * output)
{
  int i = 0;

  while (help_text[i]) {
    if (help_text[i][0])
      fputs (help_text[i], output);
    fputc ('\n', output);
    i++;
  }
  return i;
}
