TOP=/opt/project/cassini
LIB=$(TOP)/lib/original
INC=$(TOP)/include/original
CFLAGS=-Ae -g -I$(INC) -I/opt/local/include

OBJS =        new10k_V4.o window.o

.c:           cc $(CFLAGS) -c $*.c

lib:          $(OBJS)
		cc -g -o new10k_V4.exe new10k_V4.o window.o \
                                        $(LIB)/libutil.a  \
                                        -L/opt/local/lib -ldas -lm -lsunmath \
					-lfftpack

clean:
		rm *.o
