TOP=/opt/project/cassini
LIB=$(TOP)/lib/original
INC=$(TOP)/include/original
CFLAGS=-Ae -g -I$(INC) -I/opt/local/include

OBJS =        lfwr.o fft.o window.o

.c:           cc $(CFLAGS) -c $*.c

lib:          $(OBJS)
		cc -o lfwr lfwr.o fft.o window.o \
                                        $(LIB)/libutil.a  \
                                        -L/opt/local/lib -ldas -lm -lsunmath
		
clean:
		rm *.o
