#!/usr/bin/env python

import sys

for sFile in sys.argv[1:]:
	fIn = file(sFile, 'rb')
	
	i = 0
	for sLine in fIn:
		i += 1
		if not sLine.endswith('\r\n'):
			print "%s, line %d: Line ending error"%(sFile, i)
			break

	
